import axios from "axios";

// =======================================
// Axios Instance
// =======================================

const API = axios.create({
  baseURL: "http://localhost:5000/api",
  withCredentials: true,
});

// =======================================
// User APIs
// =======================================

// Get All Users
export const getAllUsers = async () => {
  const { data } = await API.get("/admin/users");
  return data;
};

// Get Single User
export const getSingleUser = async (id) => {
  const { data } = await API.get(`/admin/user/${id}`);
  return data;
};

// Approve User
export const approveUser = async (id) => {
  const { data } = await API.put(`/admin/approve/${id}`);
  return data;
};

// Delete User
export const deleteUser = async (id) => {
  const { data } = await API.delete(`/admin/delete/${id}`);
  return data;
};

// Dashboard
export const getDashboardStats = async () => {
  const { data } = await API.get("/admin/dashboard");
  return data;
};

// =======================================
// Career APIs
// =======================================

// Get All Careers
export const getAllCareers = async () => {
  const { data } = await API.get("/career");
  return data;
};

// Get Single Career
export const getSingleCareer = async (id) => {
  const { data } = await API.get(`/career/${id}`);
  return data;
};

// Add Career
export const addCareer = async (careerData) => {
  const { data } = await API.post("/career", careerData);
  return data;
};

// Update Career
export const updateCareer = async (id, careerData) => {
  const { data } = await API.put(`/career/${id}`, careerData);
  return data;
};

// Delete Career
export const deleteCareer = async (id) => {
  const { data } = await API.delete(`/career/${id}`);
  return data;
};

// =======================================
// Roadmap APIs
// =======================================

// Get All Roadmaps
// (Read-only — roadmaps are generated by the AI Career engine)
export const getAllRoadmaps = async () => {
  const { data } = await API.get("/roadmap");
  return data;
};

// =======================================
// Resource APIs
// =======================================

// Get All
export const getAllResources = async () => {
  const { data } = await API.get("/resource");
  return data;
};

// Get Single
export const getSingleResource = async (id) => {
  const { data } = await API.get(`/resource/${id}`);
  return data;
};

// Add
export const addResource = async (resourceData) => {
  const { data } = await API.post("/resource", resourceData);
  return data;
};

// Update
export const updateResource = async (id, resourceData) => {
  const { data } = await API.put(`/resource/${id}`, resourceData);
  return data;
};

// Delete
export const deleteResource = async (id) => {
  const { data } = await API.delete(`/resource/${id}`);
  return data;
};

// =======================================
// AI Recommendation APIs
// =======================================

// Get All Recommendations
export const getAllRecommendations = async () => {
  const { data } = await API.get("/recommendation");
  return data;
};

// Get Single Recommendation
export const getSingleRecommendation = async (id) => {
  const { data } = await API.get(`/recommendation/${id}`);
  return data;
};

// Delete Recommendation
export const deleteRecommendation = async (id) => {
  const { data } = await API.delete(`/recommendation/${id}`);
  return data;
};
// =======================================
// Assessment APIs
// =======================================

// Get All Assessments
export const getAllAssessments = async () => {
  const { data } = await API.get("/assessment/admin/all");
  return data;
};

// Get Single Assessment
export const getSingleAssessment = async (id) => {
  const { data } = await API.get(`/assessment/admin/${id}`);
  return data;
};

// Delete Assessment
export const deleteAssessment = async (id) => {
  const { data } = await API.delete(`/assessment/admin/${id}`);
  return data;
};